version: 0.2

run-as: root

batch:
  fast-fail: true
  build-list:
    - identifier: lambda1
      env:
        variables:
          service: test
          function: lambda1
      ignore-failure: false
    - identifier: lambda2
      env:
        variables:
          service: test
          function: lambda2
      ignore-failure: false

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: latest

  prebuild:
    commands:
      - chmod +x ./${service}/cloudformCofigurationBuilder.sh

  build:
    commands:
      - ./${service}/cloudformCofigurationBuilder.sh
      - cd ./${service}/${function}
      - npm install
      - zip -r function_${function}.zip .
      - aws s3 cp ./function_${function}.zip s3://test-pipeline-v14-outputbucket-uih7oqb3ul3s/${CODEBUILD_RESOLVED_SOURCE_VERSION}/function_${buildpath}.zip
artifacts:
  files:
    - '**/*'
  name: build_${service}_${function}.zip
  base-directory: ${service}/${function}
  
