version: 0.2

run-as: root

batch:
  fast-fail: true
  build-list:
    - identifier: lambda1
      env:
        variables:
          service: test
          function: lambda1
      ignore-failure: false
    - identifier: lambda2
      env:
        variables:
          service: test
          function: lambda2
      ignore-failure: false

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: latest

  build:
    commands:
      - . ./generate-script.sh
      - cd ./${service}/${function}
      - npm install
      - zip -r function_${function}.zip .
      - aws s3 cp ./function_${function}.zip s3://${OutputBucket}/${CODEBUILD_RESOLVED_SOURCE_VERSION}/function_${service}_${function}.zip
artifacts:
  files:
    - lambda-template.yml
    - ${CloudFormConfigurationFileName}
  name: build_${service}_${function}.zip
  base-directory: ${service}
  
