version: 0.2

run-as: root

batch:
  fast-fail: true
  build-list:
    - identifier: test
      env:
        variables:
          service: test
      ignore-failure: false

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: latest

  build:
    commands:
      - cd ./${service}
      - sam build
      - sam package --s3-bucket ${OutputBucket} --output-template-file packaged-template.yml

artifacts:
  files:
    - packaged-template.yml
  name: build_${service}.zip
  base-directory: ${service}
  
