AWSTemplateFormatVersion: "2010-09-09"
Description: "Test pipeline template"
Resources:
  CodeBuildInputBucket:
    Type: "AWS::S3::Bucket"
    Properties:
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerEnforced
        BucketName: codebuild-ap-southeast-1-a18cd90d9fc4e230311fdb760ca233f102eb7932ca0300777f65ec8d17010948-input
        ObjectLockEnabled: false
  CodeBuildOutputBucket:
    Type: "AWS::S3::Bucket"
    Properties:
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerEnforced
        BucketName: codebuild-ap-southeast-1-a18cd90d9fc4e230311fdb760ca233f102eb7932ca0300777f65ec8d17010948-output
        ObjectLockEnabled: false
  CodeBuildServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CodeBuildS3ObjectPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:PutObject'
                Resource: 
                - !Join
                  - ''
                  - - 'arn:${Partition}:s3:::'
                    - !Ref CodeBuildInputBucket
                    - /*
                - !Join
                  - ''
                  - - 'arn:${Partition}:s3:::'
                    - !Ref CodeBuildOutputBucket
                    - /*
        - PolicyName: CodeBuildS3BucketPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:GetBucketAcl'
                  - 's3:GetBucketLocation'
                Resource: 
                - !Join
                  - ''
                  - - 'arn:${Partition}:s3:::'
                    - !Ref CodeBuildInputBucket
                - !Join
                  - ''
                  - - 'arn:${Partition}:s3:::'
                    - !Ref CodeBuildOutputBucket
  
