AWSTemplateFormatVersion: '2010-09-09'
Description: 'create code pipline with simple code build stage for pipeline testing of microservice'
Resources:
  SourceBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerPreferred
        ObjectLockEnabled: false
  OutputBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerPreferred
        ObjectLockEnabled: false
  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: CodeBuildTestServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CodeBuildS3ObjectPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:PutObject'
                Resource: 
                - !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref SourceBucket
                    - /*
                - !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref OutputBucket
                    - /*
        - PolicyName: CodeBuildS3BucketPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:GetBucketAcl'
                  - 's3:GetBucketLocation'
                Resource: 
                - !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref SourceBucket
                - !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref OutputBucket
        - PolicyName: OtherCodeBuildServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:FilterLogEvents'
                  - 'logs:GetLogEvents'
                  - 'logs:CreateLogStream'
                  - 'codebuild:*'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
  CodePipelineServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: CodePipelineTestServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CodePipelineServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                  - 'codebuild:BatchGetBuildBatches'
                  - 'codebuild:StartBuildBatch'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:CreateChangeSet'
                  - 'cloudformation:DeleteChangeSet'
                  - 'cloudformation:DescribeChangeSet'
                  - 'cloudformation:ExecuteChangeSet'
                  - 'cloudformation:SetStackPolicy'
                  - 'cloudformation:ValidateTemplate'
                  - 'sns:Publish'
                  - 'iam:PassRole'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'codestar-connections:UseConnection'
                Resource: '*'
  CloudformDeployServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: CloudformDeployServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CloudformDeployServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - codedeploy:CreateApplication
                  - codedeploy:CreateDeployment
                  - codedeploy:CreateDeploymentGroup
                  - codedeploy:DeleteApplication
                  - codedeploy:DeleteDeploymentGroup
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                  - iam:AttachRolePolicy
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:DeleteRolePolicy
                  - iam:DetachRolePolicy
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:PassRole
                  - iam:PutRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                  - lambda:AddPermission
                  - lambda:CreateAlias
                  - lambda:CreateFunction
                  - lambda:DeleteAlias
                  - lambda:DeleteFunction
                  - lambda:GetAlias
                  - lambda:GetFunction
                  - lambda:ListVersionsByFunction
                  - lambda:PublishVersion
                  - lambda:RemovePermission
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:GetObject
                  - s3:PutBucketNotification
                  - sns:CreateTopic
                  - sns:DeleteTopic
                  - sns:GetTopicAttributes
                  - sns:Publish
                  - sns:Subscribe
                  - sns:Unsubscribe
                Resource: '*'
  CodeStarForPipelineConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: TestPipelineConnection
      ProviderType: GitHub
  CodeBuildService:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: 'TestCodeBuild'
      Description: 'Code build test for multi lambda microservice'
      Source:
        Type: CODEPIPELINE
      Artifacts:
        EncryptionDisabled: true
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: OutputBucket
            Type: PLAINTEXT
            Value: !Ref OutputBucket
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildServiceRole
          - Arn
      Visibility: PRIVATE
      BuildBatchConfig:
        CombineArtifacts: false
        ServiceRole:
          Fn::GetAtt:
            - CodeBuildServiceRole
            - Arn
  CodePipelineNotification:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: lemtiz@heremail.club
          Protocol: email
  CodePipelineService:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      Name: TestPipeline
      ArtifactStore: 
        Type: S3
        Location: !Ref SourceBucket
      RestartExecutionOnUpdate: false
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !GetAtt CodeStarForPipelineConnection.ConnectionArn
                FullRepositoryId: 'alunaya/test-code-pipeline'
                BranchName: 'sam'
                OutputArtifactFormat: "CODE_ZIP"
                DetectChanges: true
              OutputArtifacts:
                - Name: TestApp
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              InputArtifacts:
                - Name: TestApp
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildService
                BatchEnabled: true
                CombineArtifacts: false
              RunOrder: 1
              OutputArtifacts:
                - Name: test
        - Name: Deploy
          Actions:
            - Name: DeployTestMicroservice
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: test
              RunOrder: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: test-lambda
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                TemplatePath: test::packaged-template.yml
                RoleArn:
                  Fn::GetAtt:
                    - CloudformDeployServiceRole
                    - Arn
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: "1"
              RunOrder: 2
              Configuration:
                NotificationArn: !Ref CodePipelineNotification
                CustomData: test approval test approval
            - Name: DeleteTestMicroservice
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: test
              RunOrder: 3
              Configuration:
                ActionMode: DELETE_ONLY
                StackName: test-lambda
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn:
                  Fn::GetAtt:
                    - CloudformDeployServiceRole
                    - Arn
            - Name: DeployProdMicroservice
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: test
              RunOrder: 3
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: prod-lambda
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                TemplatePath: test::packaged-template.yml
                RoleArn:
                  Fn::GetAtt:
                    - CloudformDeployServiceRole
                    - Arn